"""Add ai_operation_metrics table for detailed cost analytics

Revision ID: 245f349b366b
Revises: a1b2c3d4e5f6
Create Date: 2025-12-29 20:52:53.902139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245f349b366b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_operation_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('CHAT_TOOL_CALL', 'CHAT_SYNTHESIS', 'CHAT_RAG_ONLY', 'INGESTION_SCENE_SUMMARY', 'INGESTION_SCRIPT_OUTLINE', 'INGESTION_CHARACTER_SHEET', 'INGESTION_EMBEDDING', name='operation_type_enum'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Model used for this operation (for multi-model analytics)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True, comment='For chat operations'),
    sa.Column('message_id', sa.UUID(), nullable=True, comment='For chat operations - links to specific message'),
    sa.Column('scene_id', sa.UUID(), nullable=True, comment='For per-scene ingestion tracking'),
    sa.Column('iteration_number', sa.Integer(), nullable=True, comment='Tool call iteration (1, 2, 3...) for CHAT_TOOL_CALL operations'),
    sa.Column('tool_name', sa.String(length=100), nullable=True, comment='Tool used in this iteration (get_scene, search_scenes, etc.)'),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Operation latency in milliseconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.scene_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_ai_operation_metrics_conversation_id'), 'ai_operation_metrics', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_created_at'), 'ai_operation_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_message_id'), 'ai_operation_metrics', ['message_id'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_metric_id'), 'ai_operation_metrics', ['metric_id'], unique=True)
    op.create_index(op.f('ix_ai_operation_metrics_operation_type'), 'ai_operation_metrics', ['operation_type'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_scene_id'), 'ai_operation_metrics', ['scene_id'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_script_id'), 'ai_operation_metrics', ['script_id'], unique=False)
    op.create_index(op.f('ix_ai_operation_metrics_user_id'), 'ai_operation_metrics', ['user_id'], unique=False)
    # Note: Removed spurious drop_index for idx_scenes_script_id_position
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_operation_metrics_user_id'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_script_id'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_scene_id'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_operation_type'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_metric_id'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_message_id'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_created_at'), table_name='ai_operation_metrics')
    op.drop_index(op.f('ix_ai_operation_metrics_conversation_id'), table_name='ai_operation_metrics')
    op.drop_table('ai_operation_metrics')
    # ### end Alembic commands ###
