"""Add token_usage table for AI analytics

Revision ID: 7b69b37063f6
Revises: 20251130_ai_system
Create Date: 2025-11-30 17:13:13.385504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b69b37063f6'
down_revision = '20251130_ai_system'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_snapshot_metadata_created_at'), table_name='scene_snapshot_metadata')
    op.drop_index(op.f('idx_snapshot_metadata_scene'), table_name='scene_snapshot_metadata')
    op.drop_table('scene_snapshot_metadata')
    op.drop_index(op.f('idx_script_versions_script_created'), table_name='script_versions')
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('idx_character_sheets_character_name'), table_name='character_sheets')
    op.drop_index(op.f('idx_character_sheets_script_id'), table_name='character_sheets')
    op.create_index(op.f('ix_character_sheets_character_name'), 'character_sheets', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_sheets_id'), 'character_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_character_sheets_script_id'), 'character_sheets', ['script_id'], unique=False)
    op.drop_index(op.f('idx_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.drop_index(op.f('idx_plot_threads_script_id'), table_name='plot_threads')
    op.create_index(op.f('ix_plot_threads_id'), 'plot_threads', ['id'], unique=False)
    op.create_index(op.f('ix_plot_threads_script_id'), 'plot_threads', ['script_id'], unique=False)
    op.drop_index(op.f('idx_scene_characters_character'), table_name='scene_characters')
    op.create_index(op.f('ix_scene_characters_character_name'), 'scene_characters', ['character_name'], unique=False)
    op.drop_index(op.f('idx_scene_relationships_payoff'), table_name='scene_relationships')
    op.drop_index(op.f('idx_scene_relationships_script_id'), table_name='scene_relationships')
    op.drop_index(op.f('idx_scene_relationships_setup'), table_name='scene_relationships')
    op.create_index(op.f('ix_scene_relationships_id'), 'scene_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_payoff_scene_id'), 'scene_relationships', ['payoff_scene_id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_script_id'), 'scene_relationships', ['script_id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_setup_scene_id'), 'scene_relationships', ['setup_scene_id'], unique=False)
    op.drop_index(op.f('idx_scene_summaries_scene_id'), table_name='scene_summaries')
    op.drop_constraint(op.f('scene_summaries_scene_id_key'), 'scene_summaries', type_='unique')
    op.create_index(op.f('ix_scene_summaries_id'), 'scene_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_scene_summaries_scene_id'), 'scene_summaries', ['scene_id'], unique=True)
    op.drop_index(op.f('idx_scenes_hash'), table_name='scenes')
    op.drop_index(op.f('idx_scenes_is_key'), table_name='scenes', postgresql_where='(is_key_scene = true)')
    op.drop_column('scenes', 'is_key_scene')
    op.drop_column('scenes', 'hash')
    op.drop_index(op.f('idx_script_outlines_script_id'), table_name='script_outlines')
    op.create_index(op.f('ix_script_outlines_id'), 'script_outlines', ['id'], unique=False)
    op.create_index(op.f('ix_script_outlines_script_id'), 'script_outlines', ['script_id'], unique=False)
    op.alter_column('scripts', 'content_blocks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full script content blocks for script-level editing',
               existing_comment='Full script content blocks',
               existing_nullable=True)
    op.alter_column('scripts', 'version',
               existing_type=sa.INTEGER(),
               comment='Optimistic locking version for compare-and-swap',
               existing_comment='Optimistic locking version for CAS',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scripts', 'updated_by',
               existing_type=sa.UUID(),
               comment='User who last updated the script',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scripts', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who last updated the script',
               existing_nullable=True)
    op.alter_column('scripts', 'version',
               existing_type=sa.INTEGER(),
               comment='Optimistic locking version for CAS',
               existing_comment='Optimistic locking version for compare-and-swap',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scripts', 'content_blocks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full script content blocks',
               existing_comment='Full script content blocks for script-level editing',
               existing_nullable=True)
    op.drop_index(op.f('ix_script_outlines_script_id'), table_name='script_outlines')
    op.drop_index(op.f('ix_script_outlines_id'), table_name='script_outlines')
    op.create_index(op.f('idx_script_outlines_script_id'), 'script_outlines', ['script_id'], unique=False)
    op.add_column('scenes', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='SHA-256 hash for change detection'))
    op.add_column('scenes', sa.Column('is_key_scene', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True if this is a pivotal scene (inciting incident, midpoint, climax)'))
    op.create_index(op.f('idx_scenes_is_key'), 'scenes', ['is_key_scene'], unique=False, postgresql_where='(is_key_scene = true)')
    op.create_index(op.f('idx_scenes_hash'), 'scenes', ['hash'], unique=False)
    op.drop_index(op.f('ix_scene_summaries_scene_id'), table_name='scene_summaries')
    op.drop_index(op.f('ix_scene_summaries_id'), table_name='scene_summaries')
    op.create_unique_constraint(op.f('scene_summaries_scene_id_key'), 'scene_summaries', ['scene_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_scene_summaries_scene_id'), 'scene_summaries', ['scene_id'], unique=False)
    op.drop_index(op.f('ix_scene_relationships_setup_scene_id'), table_name='scene_relationships')
    op.drop_index(op.f('ix_scene_relationships_script_id'), table_name='scene_relationships')
    op.drop_index(op.f('ix_scene_relationships_payoff_scene_id'), table_name='scene_relationships')
    op.drop_index(op.f('ix_scene_relationships_id'), table_name='scene_relationships')
    op.create_index(op.f('idx_scene_relationships_setup'), 'scene_relationships', ['setup_scene_id'], unique=False)
    op.create_index(op.f('idx_scene_relationships_script_id'), 'scene_relationships', ['script_id'], unique=False)
    op.create_index(op.f('idx_scene_relationships_payoff'), 'scene_relationships', ['payoff_scene_id'], unique=False)
    op.drop_index(op.f('ix_scene_characters_character_name'), table_name='scene_characters')
    op.create_index(op.f('idx_scene_characters_character'), 'scene_characters', ['character_name'], unique=False)
    op.drop_index(op.f('ix_plot_threads_script_id'), table_name='plot_threads')
    op.drop_index(op.f('ix_plot_threads_id'), table_name='plot_threads')
    op.create_index(op.f('idx_plot_threads_script_id'), 'plot_threads', ['script_id'], unique=False)
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.create_index(op.f('idx_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_character_sheets_script_id'), table_name='character_sheets')
    op.drop_index(op.f('ix_character_sheets_id'), table_name='character_sheets')
    op.drop_index(op.f('ix_character_sheets_character_name'), table_name='character_sheets')
    op.create_index(op.f('idx_character_sheets_script_id'), 'character_sheets', ['script_id'], unique=False)
    op.create_index(op.f('idx_character_sheets_character_name'), 'character_sheets', ['character_name'], unique=False)
    op.create_table('script_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('update', postgresql.BYTEA(), autoincrement=False, nullable=False, comment='Yjs binary update'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('script_versions_created_by_fkey')),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], name=op.f('script_versions_script_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('script_versions_pkey'))
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.create_index(op.f('idx_script_versions_script_created'), 'script_versions', ['script_id', 'created_at'], unique=False)
    op.create_table('scene_snapshot_metadata',
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scene_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_source', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Source: yjs, manual, import, migrated, compacted'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True, comment='User who triggered snapshot (null for automatic)'),
    sa.Column('yjs_version_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of Yjs updates at snapshot time'),
    sa.Column('yjs_latest_version_id', sa.UUID(), autoincrement=False, nullable=True, comment='Latest Yjs version included in snapshot'),
    sa.Column('yjs_checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='SHA256 checksum of Yjs state'),
    sa.Column('generation_time_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='Time taken to generate snapshot in milliseconds'),
    sa.Column('snapshot_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True, comment='Size of generated snapshot in bytes'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('scene_snapshot_metadata_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.scene_id'], name=op.f('scene_snapshot_metadata_scene_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yjs_latest_version_id'], ['scene_versions.version_id'], name=op.f('scene_snapshot_metadata_yjs_latest_version_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('scene_snapshot_metadata_pkey'))
    )
    op.create_index(op.f('idx_snapshot_metadata_scene'), 'scene_snapshot_metadata', ['scene_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_snapshot_metadata_created_at'), 'scene_snapshot_metadata', ['created_at'], unique=False)
    # ### end Alembic commands ###
