"""Add hash and is_key_scene to Scene model

Revision ID: 860a4887296c
Revises: 7b69b37063f6
Create Date: 2025-12-02 20:56:15.034109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '860a4887296c'
down_revision = '7b69b37063f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scene_snapshot_metadata', 'snapshot_source',
               existing_type=sa.VARCHAR(length=20),
               comment='Source: yjs, manual, import, migrated, compacted',
               existing_nullable=False)
    op.alter_column('scene_snapshot_metadata', 'created_by',
               existing_type=sa.UUID(),
               comment='User who triggered snapshot (null for automatic)',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'yjs_version_count',
               existing_type=sa.INTEGER(),
               comment='Number of Yjs updates at snapshot time',
               existing_nullable=False)
    op.alter_column('scene_snapshot_metadata', 'yjs_latest_version_id',
               existing_type=sa.UUID(),
               comment='Latest Yjs version included in snapshot',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'yjs_checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA256 checksum of Yjs state',
               existing_nullable=False)
    op.alter_column('scene_snapshot_metadata', 'generation_time_ms',
               existing_type=sa.INTEGER(),
               comment='Time taken to generate snapshot in milliseconds',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'snapshot_size_bytes',
               existing_type=sa.INTEGER(),
               comment='Size of generated snapshot in bytes',
               existing_nullable=True)
    op.drop_index(op.f('idx_snapshot_metadata_created_at'), table_name='scene_snapshot_metadata')
    op.create_index(op.f('ix_scene_snapshot_metadata_created_at'), 'scene_snapshot_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_scene_snapshot_metadata_scene_id'), 'scene_snapshot_metadata', ['scene_id'], unique=False)
    op.drop_constraint(op.f('scene_snapshot_metadata_yjs_latest_version_id_fkey'), 'scene_snapshot_metadata', type_='foreignkey')
    op.drop_constraint(op.f('scene_snapshot_metadata_created_by_fkey'), 'scene_snapshot_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'scene_snapshot_metadata', 'scene_versions', ['yjs_latest_version_id'], ['version_id'])
    op.create_foreign_key(None, 'scene_snapshot_metadata', 'users', ['created_by'], ['user_id'])
    op.add_column('scenes', sa.Column('hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of normalized scene content for change detection'))
    op.add_column('scenes', sa.Column('is_key_scene', sa.Integer(), nullable=False, server_default='0', comment='Manually flagged as key scene (plot point, major character moment, etc.)'))
    op.create_index(op.f('ix_scenes_hash'), 'scenes', ['hash'], unique=False)
    # Create partial index on is_key_scene (only where TRUE for sparse data optimization)
    op.create_index(
        'idx_scenes_is_key',
        'scenes',
        ['is_key_scene'],
        unique=False,
        postgresql_where=sa.text('is_key_scene = 1')
    )
    op.alter_column('script_versions', 'update',
               existing_type=postgresql.BYTEA(),
               comment='Yjs binary update',
               existing_nullable=False)
    op.alter_column('script_versions', 'created_by',
               existing_type=sa.UUID(),
               comment='User who created this update (null for system/migration)',
               existing_nullable=True)
    op.drop_index(op.f('idx_script_versions_script_id'), table_name='script_versions')
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.create_index(op.f('idx_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.alter_column('script_versions', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this update (null for system/migration)',
               existing_nullable=True)
    op.alter_column('script_versions', 'update',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Yjs binary update',
               existing_nullable=False)
    op.drop_index('idx_scenes_is_key', table_name='scenes')
    op.drop_index(op.f('ix_scenes_hash'), table_name='scenes')
    op.drop_column('scenes', 'is_key_scene')
    op.drop_column('scenes', 'hash')
    op.drop_constraint(None, 'scene_snapshot_metadata', type_='foreignkey')
    op.drop_constraint(None, 'scene_snapshot_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('scene_snapshot_metadata_created_by_fkey'), 'scene_snapshot_metadata', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('scene_snapshot_metadata_yjs_latest_version_id_fkey'), 'scene_snapshot_metadata', 'scene_versions', ['yjs_latest_version_id'], ['version_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_scene_snapshot_metadata_scene_id'), table_name='scene_snapshot_metadata')
    op.drop_index(op.f('ix_scene_snapshot_metadata_created_at'), table_name='scene_snapshot_metadata')
    op.create_index(op.f('idx_snapshot_metadata_created_at'), 'scene_snapshot_metadata', ['created_at'], unique=False)
    op.alter_column('scene_snapshot_metadata', 'snapshot_size_bytes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Size of generated snapshot in bytes',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'generation_time_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Time taken to generate snapshot in milliseconds',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'yjs_checksum',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA256 checksum of Yjs state',
               existing_nullable=False)
    op.alter_column('scene_snapshot_metadata', 'yjs_latest_version_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Latest Yjs version included in snapshot',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'yjs_version_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of Yjs updates at snapshot time',
               existing_nullable=False)
    op.alter_column('scene_snapshot_metadata', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who triggered snapshot (null for automatic)',
               existing_nullable=True)
    op.alter_column('scene_snapshot_metadata', 'snapshot_source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Source: yjs, manual, import, migrated, compacted',
               existing_nullable=False)
    # ### end Alembic commands ###
