"""add script_states table

Revision ID: dcedc562b2d2
Revises: f31e28138bc2
Create Date: 2025-12-11 21:43:18.671357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcedc562b2d2'
down_revision = 'f31e28138bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
